### ISSUE TITLE
Error on startup (Flatpak) 

### ISSUE THREAD

**Issue by biberino** [flathub/com.icanblink.blink#19]
Since the last update, Blink does no longer start.
Stdout: 
```
flatpak run com.icanblink.blink              1 ↵
Traceback (most recent call last):
  File "/app/bin/blink", line 67, in <module>
    from blink import Blink
  File "/app/lib/python3.9/site-packages/blink/__init__.py", line 32, in <module>
    from blink.chatwindow import ChatWindow
  File "/app/lib/python3.9/site-packages/blink/chatwindow.py", line 12, in <module>
    from PyQt5.QtWebKit import QWebSettings
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
```

**Comment by chienandalu** [comment]
Same here, I had to rollback to two commit ago:

```bash
flatpak update --commit=ebfc311aac104902b50928b61800d4aeb60776e96ea066cf23219526f22b9812 com.icanblink.blink

**Comment by chienandalu** [comment]
The issue by the way is that PyQt5>5.11.3 drops that module support so maybe version fixing would be needed until this is changed upstream

**Comment by syco** [comment]
commit ebfc311aac104902b50928b61800d4aeb60776e96ea066cf23219526f22b9812 was done on the 2023-04-27
git commits on that day show it was already using PyQt5 5.15.9

do you mind doing a pull request? It takes 2 hours to build

**Comment by chienandalu** [comment]
Hi @syco 

> commit ebfc311aac104902b50928b61800d4aeb60776e96ea066cf23219526f22b9812 was done on the 2023-04-27 git commits on that day show it was already using PyQt5 5.15.9

Then my assuption seems to be wrong (based on a light StackOverflow research :sweat_smile: ). When trying to downgrade to the last working version I ran

```
flatpak remote-info --log flathub com.icanblink.blink
```

And then 
```
flatpak update --commit=<commit> com.icanblink.blink
```
Until one worked. A visual summary of my results:

![image](https://github.com/flathub/com.icanblink.blink/assets/5040182/f2936bea-0008-40b6-80b4-17733e32bd51)


> do you mind doing a pull request? It takes 2 hours to build

I'd love to, but I'm afraid I don't know the convolutions of flatpak packaging or Blink dependecy tree :confused:

**Comment by syco** [comment]
Hi, please check again, yesterday build works again for me

**Comment by chienandalu** [comment]
It does! :smile: :+1: Thanks!
