### ISSUE TITLE
org.kde.Platform EOL warning on update

### ISSUE THREAD

**Issue by dtcooper** [flathub/com.icanblink.blink#28]
I get the following warning end-of-life (EOL) `org.kde.Platform` notice when I go to update blink,

```
dave@shinky:~$ sudo flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   com.icanblink.blink

Nothing to do.
```

Thanks for packaging this app!

**Comment by syco** [comment]
I'm updating the platform and the base to 5.15-23.08, when that's done I'll merge here.
But there's also a new version of blink available that I can't get to compile, and at this stage it's taking too much of my time.
If I were you I would consider moving to a different client.

**Comment by syco** [comment]
No luck, it terminates with this error:
```txt
/run/build/python3-PyQt5/sip/QtWebKit/qwebpluginfactory.sip:26:10: fatal error: qwebpluginfactory.h: No such file or directory
   26 | #include <qwebpluginfactory.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I guess blink is not compatible with io.qt.qtwebkit.BaseApp 5.15-23.08
If you want to have a look, I'll be happy to merge any working pull request.
